### ISSUE TITLE
Turn executions into movements and fix estimates

### ISSUE THREAD

**Issue by talesm** [TalesM/orcamento#26]
Fix the model, being the execution turned on movement, that can say which wallet is origin, and which is destiny, and with estimate being optional; The due date of estimate is now mandatory (the interface must default to the current day).

The execution should be now a view relating estimates with the total execution of them.

**Comment by TalesM** [comment]
#31

**Comment by talesm** [comment]
I realized the estimates being optional would be a bad idea. Not implementing it anymore.

**Comment by talesm** [comment]
Done at 91eaa919ca01509614400cfb4b7addc14545cef0. We probably will need to bump it again on #15, but it should be easier as the converter was decoupled from the OrcaDocument.

**Comment by talesm** [comment]
Just fixed some naming issues at d17448629f1a5f72a22b36a5d53a23fae97e3ef1. Now it is complete.
